# Generated by Django 3.2.13 on 2022-08-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideal_app', '0002_testimonial_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/pics'),
        ),
    ]
