# Generated by Django 3.2.13 on 2022-08-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideal_app', '0003_services_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Your_Name', models.CharField(max_length=20)),
                ('Your_Email', models.EmailField(max_length=254)),
                ('Subject', models.CharField(max_length=20)),
                ('Message', models.TextField(max_length=200)),
            ],
        ),
    ]
